[build]
  # Base directory for the build
  base = "frontend"
  # Build command - ignore TypeScript errors for now
  command = "npm install --legacy-peer-deps && DISABLE_ESLINT_PLUGIN=true npm run build"
  # Directory to publish (relative to base)
  publish = "build"
  
[[redirects]]
  # Redirect all requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Skip optional dependencies
  NPM_FLAGS = "--legacy-peer-deps"
  # Treat warnings as warnings, not errors
  CI = "false"
  # Allow TypeScript compilation even with errors
  TSC_COMPILE_ON_ERROR = "true"
  # Disable ESLint plugin during build
  DISABLE_ESLINT_PLUGIN = "true"
  # Skip source map generation for faster builds
  GENERATE_SOURCEMAP = "false"
