[build]
  # Base directory for the build
  base = "frontend"
  # Build command
  command = "npm install && npm run build"
  # Directory to publish (relative to base)
  publish = "build"
  
[[redirects]]
  # Redirect all requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Skip optional dependencies
  NPM_FLAGS = "--legacy-peer-deps"
  # Treat warnings as warnings, not errors
  CI = "false"
