[build]
  # Build command for the frontend
  command = "cd frontend && npm install && npm run build"
  # Directory to publish (the frontend build output)
  publish = "frontend/build"
  
[[redirects]]
  # Redirect all requests to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Skip optional dependencies
  NPM_FLAGS = "--legacy-peer-deps"
